name: Website CI/CD

on:
  workflow_call:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.CI_NODE_VERSION }}

      - name: Cache node_modules
        id: node-modules-cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('website/package-lock.json') }}

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: ./website

  build:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.CI_NODE_VERSION }}

      - name: Restore node_modules
        uses: actions/cache/restore@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('website/package-lock.json') }}

      - name: Build website
        run: npm run build
        working-directory: ./website

  typecheck:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.CI_NODE_VERSION }}

      - name: Restore node_modules
        uses: actions/cache/restore@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('website/package-lock.json') }}

      - name: Type check
        run: npm run typecheck
        working-directory: ./website
